### ISSUE TITLE
Readme incorrect

### ISSUE THREAD

**Issue by RitchieFarr** [GeneaLabs/nova-passport-manager#11]
In the readme the namespace is incorrect for Genealabs

`new GeneaLabs\NovaPassportManager\NovaPassportManager,` should be `new Genealabs\NovaPassportManager\NovaPassportManager,`

**Comment by mikebronner** [comment]
@RitchieFarr Thanks for reporting this. Will look into it ASAP.

**Comment by mikebronner** [comment]
Try release 0.4.0, and let me know if it works. The readme is correct, the code was wrong.
