### ISSUE TITLE
Scope of oauth_clients and oauth_tokens

### ISSUE THREAD

**Issue by wwwroth** [GeneaLabs/nova-passport-manager#12]
How come you decided to limit the scope of OAuth clients and tokens to only the current user? I'm an admin user and would like to use Nova to create a new user and then create OAuth credentials for them while logged in as my account. Then I can send those credentials to the user so they can start generating bearer tokens and making API requests.

Would you accept a PR to add a setting to this package to allow that?

**Comment by mikebronner** [comment]
Hi @wwwroth, I think a PR would be great! Thanks!
