### ISSUE TITLE
Laravel 6.x and Passport 9.x support?

### ISSUE THREAD

**Issue by ThaDaVos** [GeneaLabs/nova-passport-manager#14]
When will support for Laravel 6.x and Passport 9.x be released?

**Comment by mikebronner** [comment]
Hi @ThaDaVos, thanks for reminding me. While we won't support Laravel 6, I will add Passport 9 support soon.

**Comment by ThaDaVos** [comment]
May I ask why no Laravel 6 support? As far as I know does Passport 9 go hand in hand with Laravel 6, it's also a LTS version so many companies are moving over, including we

**Comment by mikebronner** [comment]
I do not support LTS or older versions of Laravel. Only the current Laravel version is supported. LTS is a trap. Perhaps I will write a post about it, but there are many reasons which I have enumerated on various issues in various projects (not expecting you to go look for them).

**Comment by oceanapplications** [comment]
I went ahead and tested creating a client and an access token on passport 9. It seems both of them are working fine. Are there any known changes the tool needs to fully support passport 9?

**Comment by mikebronner** [comment]
@oceanapplications thanks for confirming!

**Comment by mikebronner** [comment]
Please try the latest release 0.5.2 and let me know how it goes. :)
