### ISSUE TITLE
[BUG] t.revoke is not a function

### ISSUE THREAD

**Issue by ThaDaVos** [GeneaLabs/nova-passport-manager#16]
When I press the revoke button on a Authorized Application nothing happens and an error is shown in the console.

**Comment by ThaDaVos** [comment]
Issue seems to be here probably?
https://github.com/GeneaLabs/nova-passport-manager/blob/master/resources/js/components/Tool.vue#L251

**Comment by ThaDaVos** [comment]
The fix:
`revoke` should be `revokeAuthorizedToken`

**Comment by mikebronner** [comment]
@ThaDaVos Thanks for catching this!!

**Comment by mikebronner** [comment]
Can you give release 0.5.4 a try and let me know if it works for you?

**Comment by ThaDaVos** [comment]
Sorry I cannot in the current project as this seems to be a package to manage the personal passport stuff - it's not for admins
