### ISSUE TITLE
Issue installing package

### ISSUE THREAD

**Issue by asivaneswaran** [GeneaLabs/nova-passport-manager#4]
```Installation failed, reverting ./composer.json to its original content.


  [RuntimeException]
  Could not delete /home/vagrant/code/peaky/vendor/symfony/thanks/src/Command:
```

When trying to install symfony/thanks.

is it possible to remove from the required packages?

Thank you,

**Comment by mikebronner** [comment]
Try release 0.2.2 and let me know how that goes. However, your error seems to indicate a different issue with your project, likely related to composer. Here are some possibly related troubleshooting:
- https://stackoverflow.com/questions/26216437/error-could-not-delete-with-composer-on-vagrant
- https://github.com/googleapis/google-api-php-client/issues/1665
- https://github.com/drupal-composer/drupal-project/issues/241
- https://laracasts.com/discuss/channels/code-review/homestead-composer-issues
